### ISSUE TITLE
Title of chart don't support unicode characters

### ISSUE THREAD

**Issue by trigchen** [oliverwatkins/Iceberg-Charts#4]
As the title.

**Comment by oliverwatkins** [comment]
ok let me look into it

**Comment by oliverwatkins** [comment]
You need a font that supports unicode. There isn't one font that supports all unicode characters though.

For example if try Lucinda Sans Regular : 

		chart.setTitleFont(new Font("Lucida Sans Regular", Font.PLAIN, 32));
		chart.setTitle("\u2202 \u2201 \u2602 \u266B \u20AC");

All the unicode characters will display except the middle one.
